# Generated by Django 3.1.1 on 2020-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', related_query_name='categories', to='events.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
