# Generated by Django 3.1.1 on 2020-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
