# Generated by Django 3.1.1 on 2020-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
